wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: BCELoss
lr:
  value: 0.00025668181143312987
model_architecture:
  value: arch1
type:
  value: classification
