wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.07973288597200323
model_architecture:
  value: arch4
type:
  value: classification
