wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.07469448337571032
model_architecture:
  value: arch3
type:
  value: classification
