wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.08379951501660068
model_architecture:
  value: arch1
type:
  value: classification
