wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 128
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.09750874497787548
model_architecture:
  value: arch4
type:
  value: classification
