wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.08891197993656
model_architecture:
  value: arch2
type:
  value: classification
