wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 32
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.061074451709333365
model_architecture:
  value: arch4
type:
  value: classification
