wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.06911601943096772
model_architecture:
  value: arch5
type:
  value: classification
