wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 64
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.02516797199939689
model_architecture:
  value: arch3
type:
  value: classification
