_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: Tanh
activations:
    value: Sigmoid
batch_size:
    value: 128
early_stopping:
    value: true
epoch:
    value: 4000
loss_fn:
    value: MSELoss
lr:
    value: 0.04992996552537244
model_architecture:
    value: arch5
optimizer:
    value: mini-batch
type:
    value: regression
