wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 32
epoch:
  value: 1000
loss_fn:
  value: BCELoss
lr:
  value: 0.036097254138290034
model_architecture:
  value: arch4
type:
  value: classification
