wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 128
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.02465498767077025
model_architecture:
  value: arch2
type:
  value: classification
