wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 32
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.01184798998630028
model_architecture:
  value: arch4
type:
  value: classification
