wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 512
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.05267973909820255
model_architecture:
  value: arch1
type:
  value: classification
