wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 1000
loss_fn:
  value: MSELoss
lr:
  value: 0.04572886192521032
model_architecture:
  value: arch4
type:
  value: classification
