wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.047154859719040806
model_architecture:
  value: arch2
type:
  value: regression
