wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.030170290270723217
model_architecture:
  value: arch4
type:
  value: regression
