wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 1000
loss_fn:
  value: MSELoss
lr:
  value: 0.06706797426603321
model_architecture:
  value: arch2
type:
  value: regression
