wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 128
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.07382884166389571
model_architecture:
  value: arch5
type:
  value: regression
