wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 64
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.04048311536648026
model_architecture:
  value: arch5
type:
  value: regression
