wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.04536663435007541
model_architecture:
  value: arch5
type:
  value: regression
