wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.030668799144274252
model_architecture:
  value: arch4
type:
  value: regression
