wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 32
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.030732495036688984
model_architecture:
  value: arch3
type:
  value: regression
