wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 256
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.07470702732797031
model_architecture:
  value: arch5
type:
  value: regression
