wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 128
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.01814150827200904
model_architecture:
  value: arch4
type:
  value: regression
