wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 32
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.03868403712089087
model_architecture:
  value: arch1
type:
  value: regression
