wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.053701080401904785
model_architecture:
  value: arch3
type:
  value: regression
