wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.06260426699322008
model_architecture:
  value: arch2
type:
  value: classification
