wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.013869375950845876
model_architecture:
  value: arch5
type:
  value: classification
