wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.08642482055395552
model_architecture:
  value: arch2
type:
  value: classification
