wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 64
epoch:
  value: 1000
loss_fn:
  value: BCELoss
lr:
  value: 0.05598835986588324
model_architecture:
  value: arch3
type:
  value: classification
