wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 128
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.08265622925893457
model_architecture:
  value: arch3
type:
  value: classification
