wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 4000
loss_fn:
  value: BCELoss
lr:
  value: 0.004016889842866726
model_architecture:
  value: arch4
type:
  value: classification
