wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 256
epoch:
  value: 1000
loss_fn:
  value: BCELoss
lr:
  value: 0.08096874013956715
model_architecture:
  value: arch3
type:
  value: classification
