wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: BCELoss
lr:
  value: 0.06091886602031583
model_architecture:
  value: arch3
type:
  value: classification
