wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 32
epoch:
  value: 3000
loss_fn:
  value: BCELoss
lr:
  value: 0.09647583726222866
model_architecture:
  value: arch1
type:
  value: classification
