wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 32
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.007880508970236072
model_architecture:
  value: arch3
type:
  value: classification
