wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.05728010844688112
model_architecture:
  value: arch4
type:
  value: classification
