_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: Tanh
batch_size:
    value: 100
epoch:
    value: 100
loss_fn:
    value: <models.MLP.MLP2.Loss.MSELoss object at 0x7f196f31d690>
lr:
    value: 0.001
optimizer:
    value: null
type:
    value: classification
