_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: Tanh
batch_size:
    value: 128
epoch:
    value: 4000
loss_fn:
    value: <models.MLP.MLP2.loss.MSELoss object at 0x785083921600>
lr:
    value: 0.0001
optimizer:
    value: mini-batch
type:
    value: regression
