wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 4000
loss_fn:
  value: BCELoss
lr:
  value: 0.026392101558590383
model_architecture:
  value: arch5
type:
  value: classification
