wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 4000
loss_fn:
  value: BCELoss
lr:
  value: 0.018310556079275585
model_architecture:
  value: arch4
type:
  value: classification
