wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.07187406185096502
model_architecture:
  value: arch2
type:
  value: regression
