wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.020757724142157888
model_architecture:
  value: arch4
type:
  value: regression
