wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.020945191990330132
model_architecture:
  value: arch3
type:
  value: classification
