wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 128
epoch:
  value: 1000
loss_fn:
  value: BCELoss
lr:
  value: 0.042766843660417685
model_architecture:
  value: arch1
type:
  value: classification
