wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 256
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.07165511551272831
model_architecture:
  value: arch4
type:
  value: classification
