wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.049761272886329595
model_architecture:
  value: arch4
type:
  value: classification
