wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 32
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.06360399374565953
model_architecture:
  value: arch5
type:
  value: classification
