wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 32
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.06645931330287759
model_architecture:
  value: arch5
type:
  value: classification
