wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 256
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.08683623502109906
model_architecture:
  value: arch4
type:
  value: classification
