wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.028317405637810007
model_architecture:
  value: arch4
type:
  value: classification
