wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 32
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.05884668491993337
model_architecture:
  value: arch_base
type:
  value: classification
