wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.032552653307255826
model_architecture:
  value: arch4
type:
  value: classification
