wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 512
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.06391293624009382
model_architecture:
  value: arch5
type:
  value: classification
