wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 256
epoch:
  value: 3000
loss_fn:
  value: BCELoss
lr:
  value: 0.0040928366549811395
model_architecture:
  value: arch1
type:
  value: single_label_classification
