wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 128
epoch:
  value: 2000
loss_fn:
  value: BCELoss
lr:
  value: 0.012409954973648172
model_architecture:
  value: arch5
type:
  value: single_label_classification
