wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 64
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.06517646991448568
model_architecture:
  value: arch5
type:
  value: single_label_classification
