wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 1000
loss_fn:
  value: BCELoss
lr:
  value: 0.02413405448823411
model_architecture:
  value: arch5
type:
  value: single_label_classification
