wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 32
epoch:
  value: 4000
loss_fn:
  value: BCELoss
lr:
  value: 0.022522206781986805
model_architecture:
  value: arch2
type:
  value: single_label_classification
