wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.029498747018504516
model_architecture:
  value: arch5
type:
  value: single_label_classification
