wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.03680635054499327
model_architecture:
  value: arch5
type:
  value: single_label_classification
