wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 3000
loss_fn:
  value: BCELoss
lr:
  value: 0.01751075996093483
model_architecture:
  value: arch1
type:
  value: single_label_classification
