wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.02699106343275592
model_architecture:
  value: arch5
type:
  value: single_label_classification
