wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 512
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.028010956866095095
model_architecture:
  value: arch5
type:
  value: single_label_classification
