wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.044038159555504275
model_architecture:
  value: arch5
type:
  value: classification
