wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.00010995291280524356
model_architecture:
  value: arch3
type:
  value: regression
