wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.07221066253710764
model_architecture:
  value: arch4
type:
  value: regression
