wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 128
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.03545217892456874
model_architecture:
  value: arch2
type:
  value: classification
