wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 256
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.040563900000518426
model_architecture:
  value: arch3
type:
  value: classification
