wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 32
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.013573405378805147
model_architecture:
  value: arch3
type:
  value: classification
