_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: Tanh
activations:
    value: Linear
batch_size:
    value: 128
epoch:
    value: 3000
loss_fn:
    value: MSELoss
lr:
    value: 0.0771013806754952
model_architecture:
    value: arch2
optimizer:
    value: mini-batch
type:
    value: classification
