wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 128
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.001
model_architecture:
  value: arch1
type:
  value: single_label_classification
