wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.058572422456592006
model_architecture:
  value: arch5
type:
  value: classification
