wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 5000
loss_fn:
  value: BCELoss
lr:
  value: 0.046524897197432045
model_architecture:
  value: arch5
type:
  value: classification
