wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 64
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.051052366266083296
model_architecture:
  value: arch3
type:
  value: classification
