wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 128
epoch:
  value: 4000
loss_fn:
  value: BCELoss
lr:
  value: 0.021210255498447537
model_architecture:
  value: arch3
type:
  value: classification
