wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 64
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.0593661074612965
model_architecture:
  value: arch5
type:
  value: classification
