wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 64
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.062162260624726386
model_architecture:
  value: arch5
type:
  value: classification
