wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.014913884813313048
model_architecture:
  value: arch1
type:
  value: classification
