wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 32
epoch:
  value: 2000
loss_fn:
  value: BCELoss
lr:
  value: 0.06226491728787624
model_architecture:
  value: arch3
type:
  value: classification
