wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: BCELoss
lr:
  value: 0.0665518008721791
model_architecture:
  value: arch4
type:
  value: classification
