wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 256
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.000989635465683276
model_architecture:
  value: arch1
type:
  value: classification
