wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.036015121461127765
model_architecture:
  value: arch1
type:
  value: regression
