wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 128
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.02657776882749814
model_architecture:
  value: arch1
type:
  value: regression
