wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 32
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.05133181814596356
model_architecture:
  value: arch4
type:
  value: regression
