wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 256
epoch:
  value: 1000
loss_fn:
  value: MSELoss
lr:
  value: 0.08690235196702586
model_architecture:
  value: arch5
type:
  value: regression
