wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 32
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.05940641296339775
model_architecture:
  value: arch4
type:
  value: classification
