wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: MSELoss
lr:
  value: 0.07093078673594631
model_architecture:
  value: arch_base
type:
  value: classification
