wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 2000
loss_fn:
  value: CELoss
lr:
  value: 0.018792348893323776
model_architecture:
  value: arch2
type:
  value: classification
