wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.02298629394423233
model_architecture:
  value: arch3
type:
  value: regression
