wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.05784407729375661
model_architecture:
  value: arch3
type:
  value: regression
