wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.06392584537158438
model_architecture:
  value: arch5
type:
  value: regression
