wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 128
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.06953876250059707
model_architecture:
  value: arch5
type:
  value: regression
