wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 5000
loss_fn:
  value: BCELoss
lr:
  value: 0.04119514904239266
model_architecture:
  value: arch3
type:
  value: classification
