wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.004411874283827505
model_architecture:
  value: arch2
type:
  value: classification
