wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 128
epoch:
  value: 3000
loss_fn:
  value: BCELoss
lr:
  value: 0.011227440073380916
model_architecture:
  value: arch3
type:
  value: classification
