wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 32
epoch:
  value: 2000
loss_fn:
  value: BCELoss
lr:
  value: 0.08917433269870133
model_architecture:
  value: arch1
type:
  value: classification
