wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 32
epoch:
  value: 1000
loss_fn:
  value: BCELoss
lr:
  value: 0.007168548952747577
model_architecture:
  value: arch3
type:
  value: classification
