wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 128
epoch:
  value: 5000
loss_fn:
  value: CELoss
lr:
  value: 0.08859834892788716
model_architecture:
  value: arch5
type:
  value: classification
