wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 512
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.07531385735987618
model_architecture:
  value: arch1
type:
  value: regression
