wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.01846507229773811
model_architecture:
  value: arch2
type:
  value: regression
