wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.059614355394123554
model_architecture:
  value: arch4
type:
  value: regression
