wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: MSELoss
lr:
  value: 0.017233409082360512
model_architecture:
  value: arch4
type:
  value: regression
