wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: MSELoss
lr:
  value: 0.016450245815039354
model_architecture:
  value: arch5
type:
  value: regression
