wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.05597408598738417
model_architecture:
  value: arch1
type:
  value: regression
