wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.031747821230637435
model_architecture:
  value: arch4
type:
  value: regression
