wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 32
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.0029022599162611684
model_architecture:
  value: arch5
type:
  value: regression
