wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.04012703756367999
model_architecture:
  value: arch1
type:
  value: regression
