wandb_version: 1

activations:
  value: Sigmoid
batch_size:
  value: 128
epoch:
  value: 5000
loss_fn:
  value: MSELoss
lr:
  value: 0.08698365325758564
model_architecture:
  value: arch4
type:
  value: regression
