wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 128
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.014661031483266113
model_architecture:
  value: arch1
type:
  value: regression
