wandb_version: 1

activations:
  value: Relu
batch_size:
  value: 512
epoch:
  value: 1000
loss_fn:
  value: CELoss
lr:
  value: 0.006327200364606582
model_architecture:
  value: arch1
type:
  value: classification
