wandb_version: 1

activations:
  value: Softmax
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: MSELoss
lr:
  value: 0.0642814206911225
model_architecture:
  value: arch3
type:
  value: classification
