wandb_version: 1

activations:
  value: Linear
batch_size:
  value: 32
epoch:
  value: 4000
loss_fn:
  value: BCELoss
lr:
  value: 0.03021580590166869
model_architecture:
  value: arch3
type:
  value: classification
