wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 128
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.03420268914204323
model_architecture:
  value: arch4
type:
  value: classification
