wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 64
epoch:
  value: 2000
loss_fn:
  value: MSELoss
lr:
  value: 0.05027355593296949
model_architecture:
  value: arch4
type:
  value: classification
