wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.07032518568400747
model_architecture:
  value: arch4
type:
  value: classification
