wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 512
epoch:
  value: 3000
loss_fn:
  value: MSELoss
lr:
  value: 0.05014999108093983
model_architecture:
  value: arch5
type:
  value: classification
