wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 256
epoch:
  value: 4000
loss_fn:
  value: CELoss
lr:
  value: 0.06318272591716849
model_architecture:
  value: arch5
type:
  value: classification
