wandb_version: 1

activations:
  value: Tanh
batch_size:
  value: 128
epoch:
  value: 3000
loss_fn:
  value: CELoss
lr:
  value: 0.0747517441849405
model_architecture:
  value: arch5
type:
  value: classification
